#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-httplib2
Version  : 0.20.2
Release  : 80
URL      : https://files.pythonhosted.org/packages/37/fd/525d4c267cffe4437405fdb883c57b895ec03746337dc5ca7489d40f60d0/httplib2-0.20.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/37/fd/525d4c267cffe4437405fdb883c57b895ec03746337dc5ca7489d40f60d0/httplib2-0.20.2.tar.gz
Summary  : A comprehensive HTTP client library.
Group    : Development/Tools
License  : MIT
Requires: pypi-httplib2-license = %{version}-%{release}
Requires: pypi-httplib2-python = %{version}-%{release}
Requires: pypi-httplib2-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
Provides: httplib2
Provides: httplib2-python
Provides: httplib2-python3
BuildRequires : pypi(pyparsing)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)

%description
A comprehensive HTTP client library, ``httplib2`` supports many features left out of other HTTP libraries.
        
        **HTTP and HTTPS**
          HTTPS support is only available if the socket module was compiled with SSL support.
        
        
        **Keep-Alive**
          Supports HTTP 1.1 Keep-Alive, keeping the socket open and performing multiple requests over the same connection if possible.
        
        
        **Authentication**
          The following three types of HTTP Authentication are supported. These can be used over both HTTP and HTTPS.
        
          * Digest
          * Basic
          * WSSE
        
        **Caching**

%package license
Summary: license components for the pypi-httplib2 package.
Group: Default

%description license
license components for the pypi-httplib2 package.


%package python
Summary: python components for the pypi-httplib2 package.
Group: Default
Requires: pypi-httplib2-python3 = %{version}-%{release}

%description python
python components for the pypi-httplib2 package.


%package python3
Summary: python3 components for the pypi-httplib2 package.
Group: Default
Requires: python3-core
Provides: pypi(httplib2)
Requires: pypi(pyparsing)

%description python3
python3 components for the pypi-httplib2 package.


%prep
%setup -q -n httplib2-0.20.2
cd %{_builddir}/httplib2-0.20.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641442989
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python python2/httplib2test.py || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-httplib2
cp %{_builddir}/httplib2-0.20.2/LICENSE %{buildroot}/usr/share/package-licenses/pypi-httplib2/ad69fe8cc106ba1fc060d239d0483740bf66f1f9
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-httplib2/ad69fe8cc106ba1fc060d239d0483740bf66f1f9

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
